services:
  dnsmasq:
    build:
      context: ..
    container_name: dnsmasq
    restart: unless-stopped
    networks:
      - dns_net
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ../data:/var/log

networks:
  dns_net:
    driver: bridge
